---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudkit-console
  namespace: innabox-devel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: token-creator
rules:
- apiGroups: [""]
  resources: ["serviceaccounts/token"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudkit-console-token-creator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: token-creator
subjects:
- kind: ServiceAccount
  name: cloudkit-console
  namespace: innabox-devel
