apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cloudkit-console
  namespace: innabox-devel
  labels:
    app: cloudkit-console
spec:
  to:
    kind: Service
    name: cloudkit-console
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None
